   // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzh0pU30poslgXNZGOKYeNPd3GNizWAZQ',
    appId: '1:1037845719205:web:a9d9b889319d96e82f854c',
    messagingSenderId: '1037845719205',
    projectId: 'foodapp-9d066',
    authDomain: 'foodapp-9d066.firebaseapp.com',
    storageBucket: 'foodapp-9d066.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmpdAuMkNL6adwAbHMQLyf8LqCjaXB6CI',
    appId: '1:1037845719205:android:21a8297498d12abb2f854c',
    messagingSenderId: '1037845719205',
    projectId: 'foodapp-9d066',
    storageBucket: 'foodapp-9d066.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCznOGvsl9jGCiLapTbsXM1PKblXicSMNw',
    appId: '1:1037845719205:ios:292adbdbe86080572f854c',
    messagingSenderId: '1037845719205',
    projectId: 'foodapp-9d066',
    storageBucket: 'foodapp-9d066.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCznOGvsl9jGCiLapTbsXM1PKblXicSMNw',
    appId: '1:1037845719205:ios:292adbdbe86080572f854c',
    messagingSenderId: '1037845719205',
    projectId: 'foodapp-9d066',
    storageBucket: 'foodapp-9d066.firebasestorage.app',
    iosBundleId: 'com.example.foodapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzh0pU30poslgXNZGOKYeNPd3GNizWAZQ',
    appId: '1:1037845719205:web:34c315e29cee02b92f854c',
    messagingSenderId: '1037845719205',
    projectId: 'foodapp-9d066',
    authDomain: 'foodapp-9d066.firebaseapp.com',
    storageBucket: 'foodapp-9d066.firebasestorage.app',
  );
}
